# Generated by Django 3.2.25 on 2025-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2250)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4000)),
                ('output', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LungCancerCtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2250)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4000)),
                ('output', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LungCancerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('yellow_fingers', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('peer_pressure', models.IntegerField()),
                ('chronic_disease', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('allergy', models.IntegerField()),
                ('wheezing', models.IntegerField()),
                ('alcohol_consuming', models.IntegerField()),
                ('coughing', models.IntegerField()),
                ('shortness_of_breath', models.IntegerField()),
                ('swallowing_difficulty', models.IntegerField()),
                ('chest_pain', models.IntegerField()),
                ('lung_cancer', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
            ],
        ),
    ]
